<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\..\common.props" />
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>iOne.Workflow</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\iOne.Workflow.Application.Contracts\iOne.Workflow.Application.Contracts.csproj" />
    <ProjectReference Include="..\iOne.Workflow.Application\iOne.Workflow.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="9.3.6" />
  </ItemGroup>
</Project>
