<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\..\common.props" />
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>iOne.PartnerIntegration</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\common\domain\iOne.Domain.Shared\iOne.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\src\common\domain\iOne.Domain\iOne.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application.Contracts" Version="9.3.6" />
  </ItemGroup>
</Project>
