<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>Volo.Abp.AuditLogging.Application</AssemblyName>
    <PackageId>Volo.Abp.AuditLogging.Application</PackageId>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <RootNamespace />
    <Version>9.3.6</Version>
    <CopyLocalLockFileAssemblies>True</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Volo.Abp.AuditLogging.Application.Contracts\Volo.Abp.AuditLogging.Application.Contracts.csproj" />
    <ProjectReference Include="..\Volo.Abp.AuditLogging.Domain\Volo.Abp.AuditLogging.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.AutoMapper" Version="9.3.6" />
    <PackageReference Include="Volo.Abp.Ddd.Application" Version="9.3.6" />
    <PackageReference Include="Volo.Abp.Ddd.Application.Contracts" Version="9.3.6" />
  </ItemGroup>
</Project>

