<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>Volo.Abp.AuditLogging.MongoDB</AssemblyName>
    <PackageId>Volo.Abp.AuditLogging.MongoDB</PackageId>
    <RootNamespace />
    <Version>9.3.6</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Volo.Abp.AuditLogging.Domain\Volo.Abp.AuditLogging.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.MongoDB" Version="9.3.6" />
  </ItemGroup>

</Project>
